# Base image
FROM node:20-alpine

WORKDIR /app

# Copy and install deps
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

EXPOSE 5173

# Start Vite dev server
CMD ["npm", "run", "dev"]
