FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache ffmpeg


# Copy package files
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "run", "start:prod"]
